apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  namespace: c60f49-dev
  name: backend-dc
  labels:
    app: demo
spec:
  selector:
    name: demo-backend
    app: demo
  replicas: 1
  template:
    metadata:
      labels:
        name: demo-backend
        app: demo
    spec:
      containers:
        - name: postgresql
          image: 'image-registry.openshift-image-registry.svc:5000/c60f49-dev/postgres:1.7'
          imagePullPolicy: Always
          restartPolicy: Always
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /db/data
          volumeMounts:
            - mountPath: /db
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}
  strategy:
    type: Recreate
