apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  namespace: c60f49-dev
  name: drupal
spec:
  selector:
    app: drupal
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      volumes:
        - name: app-codes
          emptyDir: {}
        - name: app-files
          persistentVolumeClaim:
            claimName: backend-pcv
      containers:
        - name: drupal
          image: >-
            image-registry.openshift-image-registry.svc:5000/c60f49-dev/drupal@sha256:8a436250e196a15a6ebb510e5edb2eb93aca9e24d64bbe3dfa5ec0213ed56569
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: backend-service
            - name: POSTGRES_PORT
              value: '5432'
          lifecycle:
            postStart:
                exec:
                  command:
                    - "bin/sh"
                    - "-c"
                    - >
                      cp -rf /code/. /app;
                      mkdir -p /contents/public;
                      mkdir -p /contents/private;
                      chmod 775 /contents/public;
                      chmod 775 /contents/private;
                      ln -s /contents/public /app/web/sites/default/files;
                      ln -s /contents/private /app/private;
        - name: nginx
          image: >-
            image-registry.openshift-image-registry.svc:5000/c60f49-dev/nginx@sha256:280a332cc325190a2b2aedf7eeec14b2ac3e4fe7dd7a6c366d93aa5c31eb953c
          ports:
            - name: http
              containerPort: 8080
