apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  namespace: c60f49-dev
  name: drupal
spec:
  selector:
    app: drupal
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      volumes:
        - name: app-codes
          emptyDir: {}
        - name: app-files
          persistentVolumeClaim:
            claimName: frontend-pcv
      containers:
        - name: drupal
          image: >-
            image-registry.openshift-image-registry.svc:5000/c60f49-dev/drupal:1.2
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 512Mi
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: backend-service
            - name: POSTGRES_PORT
              value: '5432'
          lifecycle:
            postStart:
                exec:
                  command:
                    - "bin/sh"
                    - "-c"
                    - >
                      cp -rf /code/. /app;
                      mkdir -p /contents/public;
                      mkdir -p /contents/private;
                      chmod 775 /contents/public;
                      chmod 775 /contents/private;
                      ln -s /contents/public /app/web/sites/default/files;
                      ln -s /contents/private /app/private;
                      drush cr;
                      drush updb -y;
                      drush cr;
        - name: nginx
          image: >-
            image-registry.openshift-image-registry.svc:5000/c60f49-dev/nginx:5.0
          ports:
            - name: http
              containerPort: 8080
